name: swype
description: "The World of dating!"

publish_to: "none"

version: 1.0.3+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  page_transition: ^2.1.0
  page_animation_transition: ^1.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_card_swiper: ^7.0.1
  dropdown_button2: ^2.3.9
  sms_autofill: ^2.4.0
  audioplayers: ^6.1.0
  local_auth: ^2.3.0
  package_info_plus: ^8.0.2
  dropdown_search: ^6.0.1
  url_launcher: ^6.3.0
  bottom_picker: ^2.8.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  ably_flutter: ^1.2.34
  vibration: ^2.0.0
  sign_in_with_apple: ^6.1.3
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/gif/
    - assets/icon/
    - assets/sounds/

  fonts:
    - family: SK-Modernist
      fonts:
        - asset: assets/fonts/Sk-Modernist-Regular.otf
          weight: 400
        - asset: assets/fonts/Sk-Modernist-Mono.otf
          weight: 300
        - asset: assets/fonts/Sk-Modernist-Bold.otf
          weight: 700
